/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from 'kysely'

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>

export type Json = JsonValue

export type JsonArray = JsonValue[]

export type JsonObject = {
  [x: string]: JsonValue | undefined
}

export type JsonPrimitive = boolean | number | string | null

export type JsonValue = JsonArray | JsonObject | JsonPrimitive

export type Origin = 'Donor Colony' | 'Fragment of Opportunity' | 'Nursery'

export type Timestamp = ColumnType<Date, Date | string, Date | string>

export type UserRole = 'Admin' | 'Operator' | 'Staff'

export interface Operators {
  id: string
  name: string
  region: string
}

export interface OperatorsSites {
  id: Generated<number>
  operator: string
  site: string
}

export interface OutplantDays {
  createdAt: Generated<Timestamp>
  date: Timestamp
  id: Generated<number>
  operator: string
  originalData: Json
  site: string
}

export interface Outplants {
  count: number
  createdAt: Generated<Timestamp>
  day: number | null
  id: Generated<number>
  morph: string
  notes: string | null
  origin: Origin
  originalData: Json
  species: string
}

export interface Reefs {
  id: string
  name: string
  region: string
}

export interface Regions {
  color: string
  id: string
  name: string
}

export interface Sites {
  id: string
  name: string
  reef: string
}

export interface Species {
  genus: string
  id: string
  species: string | null
}

export interface Users {
  email: string | null
  id: Generated<string>
  name: string | null
  operatorId: string | null
  password: string
  resetToken: string | null
  resetTokenExpiresAt: Timestamp | null
  role: Generated<UserRole>
}

export interface DB {
  operators: Operators
  operatorsSites: OperatorsSites
  outplantDays: OutplantDays
  outplants: Outplants
  reefs: Reefs
  regions: Regions
  sites: Sites
  species: Species
  users: Users
}
